# [custom.task_count_pending]
# command = "bash $HOME/dotfiles/scripts/todo_inbox_counter.sh"
# when = "test $(bash $HOME/dotfiles/scripts/todo_inbox_counter.sh) -gt 0"
# symbol = "ğŸ“Œ"
# description = "Count of inbox tasks"

# [custom.task_count_urgent]
# command = "bash $HOME/dotfiles/scripts/todo_urgent_counter.sh"
# when = "test $(bash $HOME/dotfiles/scripts/todo_urgent_counter.sh) -gt 0"
# symbol = "âš¡ï¸"
# description = "Count of urgent tasks"

# [custom.task_count_pending]
# command = "task count rc.gc=off rc.verbose=nothing tags:in status:pending"
# when = "test $(task count rc.gc=off rc.verbose=nothing tags:in status:pending) -gt 0"
# symbol = "ğŸ“Œ"
# description = "Count of inbox Taskwarrior tasks"

# starship.toml

# [custom.task_count_pending]
# command = "python3 $HOME/dotfiles/scripts/python_todo_counter.py"
# when = "test $(python3 $HOME/dotfiles/scripts/python_todo_counter.py) -gt 0"
# symbol = "ğŸ“Œ"
# description = "Count of inbox tasks"
